Create C.cpp
Falier77777/MIPT-code pull request #4
Opened 2020-10-09 02:52 UTC by AlexFreik

2020-10-11 14:49 UTC, alexgryzlov requested changes
Добавь, пожалуйста, ссылку на посылку в контесте

2020-11-25 06:48 UTC, AlexFreik commented on 3_sem/Algorithms/1_contest/C.cpp
> +            patterns.rbegin()->append(1, pat[cnt]);
поправлю

2020-11-25 06:51 UTC, AlexFreik commented on 3_sem/Algorithms/1_contest/C.cpp
> +                      std::vector<size_t> &patt_places) {
Создам класс бора, но все еще не понимаю проблему out параметров. Попробовал поискать в гугле про это, но не нашел. Какая идейно разница передавать параметры через возвращаемое значение или через ссылку из аргументов? Если в документации написать, что это ссылка для возвращаемого значения, проблем не  вижу. И главный аргумент, что так проще писать и не надо париться с тем что создаешь копию лишний раз

2020-11-25 06:52 UTC, AlexFreik commented on 3_sem/Algorithms/1_contest/C.cpp
> +                patterns.push_back(std::string());
переделаю

2020-11-25 06:58 UTC, AlexFreik commented on 3_sem/Algorithms/1_contest/C.cpp
> +    std::vector<std::pair<size_t, size_t>> id;
Хороший совет, поправлю

2020-11-25 07:00 UTC, AlexFreik commented on 3_sem/Algorithms/1_contest/C.cpp
> +}
уберу

2020-11-25 07:00 UTC, AlexFreik commented on 3_sem/Algorithms/1_contest/C.cpp
> +    curr->id.push_back({id_number, patt.size()});
заменил

2020-11-25 07:01 UTC, AlexFreik commented on 3_sem/Algorithms/1_contest/C.cpp
> +}
заменил

2020-11-25 07:02 UTC, AlexFreik commented on 3_sem/Algorithms/1_contest/C.cpp
> +                  std::vector<uint32_t> &ans) {
мне так больше нравится

2020-11-25 07:10 UTC, AlexFreik commented on 3_sem/Algorithms/1_contest/C.cpp
> +    ~Node();
переделаю

2020-11-25 07:30 UTC, AlexFreik commented on 3_sem/Algorithms/1_contest/C.cpp
> +    }
сделаю

2020-11-25 18:06 UTC, alexgryzlov commented on 3_sem/Algorithms/1_contest/C.cpp
> +                      std::vector<size_t> &patt_places) {
Обычно они затрудняют работу с методом, и все основные code style'ы рекомендуют их не использовать.
По поводу документации - думаю ты по своему опыту можешь понять, насколько редко пользователь смотрит в документацию.
https://stackoverflow.com/a/1434418
https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs

2020-11-25 18:09 UTC, alexgryzlov commented on 3_sem/Algorithms/1_contest/C.cpp
>          delete kv.second;
Забыл написать при первом ревью - в 17-ых плюсах появилась удобная штука structured bindings (https://en.cppreference.com/w/cpp/language/structured_binding). Можно писать ```for (auto [letter, child] : childs) delete child; ```

2020-11-25 18:09 UTC, alexgryzlov approved these changes

2020-11-25 18:10 UTC, alexgryzlov commented
По поводу out параметров - это не моя вредность, а плюс минус принятый кодстайл, поэтому рекомендую тебе отучиваться их использовать.

2020-11-25 18:10 UTC, merged

2020-11-25 19:44 UTC, AlexFreik commented
> По поводу out параметров - это не моя вредность, а плюс минус принятый кодстайл, поэтому рекомендую тебе отучиваться их использовать.

А в чем именно состоит проблема?

2020-11-26 06:13 UTC, AlexFreik commented on 3_sem/Algorithms/1_contest/C.cpp
>          delete kv.second;
круто) так удобнее и читабельнее